{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "87b24305-78b1-4d88-83a9-733011167427",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras import layers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fad1be58-28d1-4d7c-926d-dc23da6bdd79",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder\n",
    "from sklearn.compose import make_column_selector, make_column_transformer\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.model_selection import cross_val_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d20a532b-3222-4f72-a230-fd033a1d4b7b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f13ab9f1-1e4e-4335-a5f5-608da6ede63d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv(r\"C:\\Users\\luis_\\Documents\\GitHub\\data-science-projects\\house-price-prediction\\train.csv\")\n",
    "df_test = pd.read_csv(r\"C:\\Users\\luis_\\Documents\\GitHub\\data-science-projects\\house-price-prediction\\test.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b1dc7f6b-cd3d-4d03-9221-34b472eb5fca",
   "metadata": {},
   "source": [
    "## Model Improvements\n",
    "\n",
    "- Added GridSearchCV.\n",
    "- Added RandomizedSearchCV."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8f47842e-6e4a-4d58-80b4-3f927a9e2fb6",
   "metadata": {},
   "source": [
    "## Visualizing the Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dcd2f6b7-48d0-4978-b27a-38630966fc76",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<AxesSubplot:xlabel='SalePrice', ylabel='Count'>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYUAAAEGCAYAAACKB4k+AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAXaElEQVR4nO3dfbBcdZ3n8feXYNAFBoK5S4KACYrMKutEuKCMDxvFcYCKUacAE6YUM+jFGZnSYksXhi11p8oqGRUfd9CoPFglEAQZ44wzyKADtbMjkEQMD0kggVCEBHKBCK4zhQS++8c596Rz032fcrtPd/r9quq6p3/n6Zt03/7cc36nfycyE0mSAParuwBJUvcwFCRJFUNBklQxFCRJFUNBklTZv+4C9sbs2bNz3rx5dZchST1l9erVT2bmQLN5PR0K8+bNY9WqVXWXIUk9JSIeaTXP00eSpIqhIEmqGAqSpIqhIEmqGAqSpIqhIEmqGAqSpIqhIEmqtC0UIuKKiNgeEfc2tK2IiLvLx+aIuLtsnxcR/9Ew75vtqkuS1Fo7v9F8FfAN4HsjDZn5/pHpiPgS8EzD8psyc0Eb6+kJ5ywbYuvwjj3ajxiYxTVXLq+hIkn9pG2hkJm3R8S8ZvMiIoCzgXe0a/+9auvwDuYsvnDP9pWX1VCNpH5TV5/CW4EnMvPBhrb5EfHLiLgtIt7aasWIGIqIVRGxanh4uP2VSlIfqSsUlgLXNjzfBhydmW8ALgSuiYjfa7ZiZi7PzMHMHBwYaDrInyRpijoeChGxP/AnwIqRtsx8LjOfKqdXA5uA13S6Nknqd3UcKbwTWJ+ZW0YaImIgImaU08cAxwIP1VCbJPW1dl6Sei3wb8BxEbElIs4rZy1h91NHAG8D1paXqN4AfDQzn25XbZKk5tp59dHSFu0fatJ2I3Bju2rZF6xfdz8LF521R7uXqkqaTj1957V+8jz7eamqpLZzmAtJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUsVQkCRVDAVJUqVtoRARV0TE9oi4t6HtsxHxWETcXT7OaJh3cURsjIgNEfHH7apLktRaO48UrgJOa9L+5cxcUD5+AhARrwWWAK8r1/nbiJjRxtokSU20LRQy83bg6Qku/h7gusx8LjMfBjYCJ7erNklSc3X0KVwQEWvL00uzyrZXAI82LLOlbNtDRAxFxKqIWDU8PNzuWiWpr3Q6FC4HXgUsALYBX5rsBjJzeWYOZubgwMDANJcnSf2to6GQmU9k5guZ+SLwbXadInoMOKph0SPLNklSB3U0FCJibsPT9wEjVyatBJZExAERMR84Frizk7VJkmD/dm04Iq4FFgKzI2IL8BlgYUQsABLYDJwPkJn3RcT1wP3ATuBjmflCu2qTJDXXtlDIzKVNmr87xvKfAz7XrnokSeNrWyioXucsG2Lr8I6m844YmMU1Vy7vcEWSeoGhsI/aOryDOYsvbD5v5WUdrkZSr3DsI0lSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxVCQJFUMBUlSxTuv9bj16+5n4aKz9mh/4MGNzKmhHkm9rW2hEBFXAIuA7Zl5fNn2BeDdwO+ATcCyzPx1RMwD1gEbytV/kZkfbVdt+5Ln2a/pbTfvuXSohmok9bp2nj66CjhtVNstwPGZ+XrgAeDihnmbMnNB+TAQJKkGbQuFzLwdeHpU208zc2f59BfAke3avyRp8ursaP4z4B8bns+PiF9GxG0R8da6ipKkflZLR3NEXALsBL5fNm0Djs7MpyLiRODvIuJ1mflsk3WHgCGAo48+ulMlT7tzlg2xdXjHHu12EEuqU8dDISI+RNEBfWpmJkBmPgc8V06vjohNwGuAVaPXz8zlwHKAwcHB7FDZ027r8A47iCV1nY6ePoqI04BPAYsz898b2gciYkY5fQxwLPBQJ2uTJLX3ktRrgYXA7IjYAnyG4mqjA4BbIgJ2XXr6NuCvI+J54EXgo5n5dNMNS5Lapm2hkJlLmzR/t8WyNwI3tqsWSdLEOMyFJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKvtPZKGIeHNm/ut4beoN69fdz8JFZ+3RfsTALK65cnkNFUnqFhMKBeDrwAkTaNtNRFwBLAK2Z+bxZdthwApgHrAZODszd0REAF8FzgD+HfhQZq6ZYH2ahOfZjzmLL9yjfevKy2qoRlI3GTMUIuIU4A+BgYho/BT5PWDGBLZ/FfAN4HsNbRcBt2bm5yPiovL5/wBOB44tH28ELi9/SpI6ZLw+hZnAQRThcXDD41ngzPE2npm3A0+Pan4PcHU5fTXw3ob272XhF8ChETF3Av8GSdI0GfNIITNvA26LiKsy85Fp2ufhmbmtnH4cOLycfgXwaMNyW8q2bQ1tRMQQMARw9NFHT1NJkiSYeJ/CARGxnKIfoFonM9+xNzvPzIyInOQ6y4HlAIODg5NaV5I0tomGwg+AbwLfAV7Yy30+ERFzM3NbeXpoe9n+GHBUw3JHlm2SpA6ZaCjszMzLp2mfK4Fzgc+XP3/U0H5BRFxH0cH8TMNpJklSB0w0FH4cEX8B3AQ8N9KYmaM7kXcTEdcCC4HZEbEF+AxFGFwfEecBjwBnl4v/hOJy1I0Ul6Qum/g/Q5I0HSYaCueWPz/Z0JbAMWOtlJlLW8w6tcmyCXxsgvVIktpgQqGQmfPbXYgkqX4THebig83aM/N7zdolSb1poqePTmqYfinF6Z817P5NZUlSj5vo6aO/bHweEYcC17WjIElSfaY6dPZvAfsZJGkfM9E+hR9TXG0ExUB4/wW4vl1FSZLqMdE+hS82TO8EHsnMLW2oR5JUowmdPioHxltPMULqLOB37SxKklSPCYVCRJwN3AmcRfEN5DsiYtyhsyVJvWWip48uAU7KzO0AETEA/DNwQ7sKkyR13kSvPtpvJBBKT01iXUlSj5jokcI/RcTNwLXl8/dTDGAnSdqHjHeP5ldT3CntkxHxJ8Bbyln/Bny/3cVJkjprvCOFrwAXA2TmD4EfAkTEfy3nvbuNtUmSOmy8foHDM/Oe0Y1l27y2VCRJqs14oXDoGPNeNo11SJK6wHihsCoiPjK6MSI+DKxuT0mSpLqM16fwCeCmiPhTdoXAIDATeF8b65Ik1WDMUMjMJ4A/jIi3A8eXzf+QmT9re2WSpI6b6P0Ufg78vM21SJJqNtEvr02biDgOWNHQdAzwaYpO7Y8Aw2X7X2WmX5CTpA7qeChk5gZgAUBEzAAeA24ClgFfzswvtl5bktROdY9fdCqwKTMfqbkOSRL1h8ISdo2nBHBBRKyNiCsiYlazFSJiKCJWRcSq4eHhZotIkqaotlCIiJnAYuAHZdPlwKsoTi1tA77UbL3MXJ6Zg5k5ODAw0IlSJalv1HmkcDqwprzslcx8IjNfyMwXgW8DJ9dYmyT1pTpDYSkNp44iYm7DvPcB93a8Iknqcx2/+gggIg4E/gg4v6H5byJiAZDA5lHzJEkdUEsoZOZvgZePavtAHbVIknapJRTUndavu5+Fi87ao/2IgVlcc+XyGiqS1GmGgirPsx9zFl+4R/vWlZfVUI2kOhgKmrJzlg2xdXhH03keXUi9yVCYBq0+HPf1D8atwzuaHlmARxdSrzIUpkGrD0c/GCX1GkOhjVp13AI88OBG5nS4Hkkaj6HQRq06bgHuuXSow9VMXatwM9ikfY+hoHG1CrdeCjZJE1P3KKmSpC5iKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKoaCJKliKEiSKrUNiBcRm4HfAC8AOzNzMCIOA1YA84DNwNmZ2fzWXpKkaVf3kcLbM3NBZg6Wzy8Cbs3MY4Fby+eSpA6pOxRGew9wdTl9NfDe+kqRpP5TZygk8NOIWB0RIwPzH56Z28rpx4HDR68UEUMRsSoiVg0PD3eqVknqC3XeZOctmflYRPxn4JaIWN84MzMzInL0Spm5HFgOMDg4uMd8SdLU1XakkJmPlT+3AzcBJwNPRMRcgPLn9rrqk6R+VEsoRMSBEXHwyDTwLuBeYCVwbrnYucCP6qhPkvpVXaePDgduioiRGq7JzH+KiLuA6yPiPOAR4Oya6pOkvlRLKGTmQ8AfNGl/Cji18xVJkqD7LkmVJNXIUJAkVQwFSVLFUJAkVQwFSVLFUJAkVeoc5kJ96JxlQ2wd3nM09CMGZnHNlctrqEhSI0NBHbV1eAdzFl+4Z/vKy2qoRtJohoLaYv26+1m46Kw92h94cCNzaqhH0sQYCmqL59mv6RHBPZcONVlaUrewo1mSVDEUJEkVQ0GSVDEUJEkVO5rVFVpdreT3F6TOMhTUFVpdreT3F6TO8vSRJKliKEiSKoaCJKliKEiSKh0PhYg4KiJ+HhH3R8R9EfHxsv2zEfFYRNxdPs7odG2S1O/quPpoJ/DfM3NNRBwMrI6IW8p5X87ML9ZQk/YhDs8tTV3HQyEztwHbyunfRMQ64BWdrkP7Lofnlqau1j6FiJgHvAG4o2y6ICLWRsQVETGrvsokqT/VFgoRcRBwI/CJzHwWuBx4FbCA4kjiSy3WG4qIVRGxanh4uFPlSlJfqCUUIuIlFIHw/cz8IUBmPpGZL2Tmi8C3gZObrZuZyzNzMDMHBwYGOle0JPWBOq4+CuC7wLrMvKyhfW7DYu8D7u10bZLU7+q4+ujNwAeAeyLi7rLtr4ClEbEASGAzcH4NtUlSX6vj6qP/A0STWT/pdC2SpN35jWZJUsVQkCRVDAVJUsWb7KireUc2qbMMBXW1Vndk+9mlH24aFgAPPLiROe0uTNpHGQrqSa3CAuCeS4c6XI2077BPQZJUMRQkSRVDQZJUsU9hElrdvMWOzd7glUzS+AyFSWh18xY7NntDq85pb74j7WIoNOERgcbS6v0BHnWo9xkKTXhEoLG0en+ARx3qfXY0S5IqHilILXgaUf3IUJBa8DSi+pGhIE0jL3tVrzMU1PdafZBP5TSRl72q1/V1KHjOWND6g3w6TxN5BKFe0deh4DljdcpkhwB/5OGNvHL+q/doN0TUbn0dClLdxjpKmexpqFZHvgaJJqPrQiEiTgO+CswAvpOZn6+5JKkntDryrbM/w6Dae53+P+yqUIiIGcD/Bv4I2ALcFRErM/P+eiuTNBXdGFS9ptP/h10VCsDJwMbMfAggIq4D3gMYChKtO6yh9QUSrdaZzn6L6bpoYyrjSrVax36ZqYnMrLuGSkScCZyWmR8un38AeGNmXtCwzBAw0hN8HPAU8GSna52C2VjndOuVWq1zevVKndC9tb4yMweazei2I4VxZeZyoIr5iFiVmYM1ljQh1jn9eqVW65xevVIn9FatI7ptQLzHgKManh9ZtkmSOqDbQuEu4NiImB8RM4ElwMqaa5KkvtFVp48yc2dEXADcTHFJ6hWZed84q/VKj5F1Tr9eqdU6p1ev1Am9VSvQZR3NkqR6ddvpI0lSjQwFSdIumdmTD+A0YAOwEbiojfu5AtgO3NvQdhhwC/Bg+XNW2R7A18qa1gInNKxzbrn8g8C5De0nAveU63yNXaf0mu5jjDqPAn5O8UW/+4CPd3GtLwXuBH5V1vq/yvb5wB3l9lcAM8v2A8rnG8v58xq2dXHZvgH44/HeH632MU69M4BfAn/frXUCm8vX5m5gVRe/9ocCNwDrgXXAKV1a53Hl/+XI41ngE91Y67R/5nVyZ9NWdPFLugk4BphJ8eHy2jbt623ACeweCn9D+QsMXARcWk6fAfxj+QZ5E3BHw4v8UPlzVjk98ma6s1w2ynVPH2sfY9Q5d+SNCBwMPAC8tktrDeCgcvolFB9+bwKuB5aU7d8E/ryc/gvgm+X0EmBFOf3a8rU/gOJDdFP53mj5/mi1j3HqvRC4hl2h0HV1UoTC7FFt3fjaXw18uJyeSRESXVdnk8+bx4FXdnut0/KZ18mdTVvRxV8XNzc8vxi4uI37m8fuobABmFtOzwU2lNPfApaOXg5YCnyrof1bZdtcYH1De7Vcq31MouYfUYwh1dW1Av8JWAO8keKbn/uPfo0prkY7pZzev1wuRr/uI8u1en+U6zTdxxj1HQncCrwD+PuxtlFznZvZMxS66rUHDgEepvyLuFvrbFL3u4B/7YVap+PRq30KrwAebXi+pWzrlMMzc1s5/Thw+Dh1jdW+pUn7WPsYV0TMA95A8Rd4V9YaETMi4m6KU3O3UPzF/OvM3Nlk+1VN5fxngJdP4d/w8jH20cpXgE8BL5bPx9pGnXUm8NOIWF0OBQPd99rPB4aBKyPilxHxnYg4sAvrHG0JcO042+mWWvdar4ZC18gizrNb9hERBwE3Ap/IzGenup2pmug+MvOFzFxA8Zf4ycDvt7OuqYiIRcD2zFxddy0T8JbMPAE4HfhYRLytcWaXvPb7U5yKvTwz3wD8luL0yGS2sdcm+fs0E1gM/GBvtjNVndjHaL0aCnUPh/FERMwFKH9uH6eusdqPbNI+1j5aioiXUATC9zPzh91c64jM/DVFB/kpwKERMfKFysbtVzWV8w+hGAhxsv+Gp8bYRzNvBhZHxGbgOopTSF/twjrJzMfKn9uBmyiCttte+y3Alsy8o3x+A0VIdFudjU4H1mTmE+NspxtqnRa9Ggp1D4exkuKKAsqfP2po/2AU3gQ8Ux4G3gy8KyJmRcQsinOUN5fzno2IN0VEAB8cta1m+2iqXP+7wLrMbBxovRtrHYiIQ8vpl1H0fayjCIczW9Q6sv0zgZ+Vf0GtBJZExAERMR84lqLzrun7o1yn1T72kJkXZ+aRmTmv3MbPMvNPu63OiDgwIg4emaZ4ze6ly177zHwceDQijiubTqW4Wq6r6hxlKbtOHY21nW6odXp0sgNjOh8Uvf0PUJyLvqSN+7kW2AY8T/GXznkU53xvpbhk7J+Bw8plg+ImQZsoLjUbbNjOn1FcerYRWNbQPkjxC7wJ+Aa7Lktruo8x6nwLxWHmWnZdRndGl9b6eopLPNeW2/t02X4MxYflRorD9QPK9peWzzeW849p2NYlZT0bKK/eGOv90WofE3gfLGTX1UddVWe57K/YdYnvJWO9LjW/9guAVeVr/3cUV+R0XZ3lOgdSHLUd0tDWlbVO58NhLiRJlV49fSRJagNDQZJUMRQkSRVDQZJUMRQkSRVDQX0vIi6JiPsiYm1E3B0Rbxxj2asi4sxW8xuWebjc1pqIOKXFcn8dEe/c2/ql6dRVt+OUOq38wF5EMcLscxExm2L0zr31ycy8ISLeRTEI2utH7XdGZn56GvYjTSuPFNTv5gJPZuZzAJn5ZGZujYhPR8RdEXFvRCwvv3W6m4g4MSJui2IQuptHhiYY5Xbg1eXymyPi0ohYA5zVeNQRESdFxP+NiF9FxJ0RcXAUgwZ+oaxjbUSc377/BqlgKKjf/RQ4KiIeiIi/jYj/VrZ/IzNPyszjgZdRHE1Uohhn6uvAmZl5IsXNmD7XZPvvpviG64inMvOEzLyuYVszKW6k8/HM/APgncB/UHx7/pnMPAk4CfhIOUyG1DaePlJfy8z/FxEnAm8F3g6siIiLgN9ExKco7vdwGMXwET9uWPU44HjglvIgYgbFcCgjvhAR/5NiqOjzGtpXNCnjOGBbZt5V1vQsQHnq6fUNfRiHUIyb9PDU/8XS2AwF9b3MfAH4F+BfIuIe4HyKPoDBzHw0Ij5LMa5RowDuy8ymnciUfQpN2n87idIC+MvMvHkS60h7xdNH6msRcVxEHNvQtIBi0DqAJ6O4P0Wzq402AAMjVxZFxEsi4nVTLGMDMDciTiq3dXAUw2bfDPx5eaqKiHhNOQqq1DYeKajfHQR8vRzKeyfFSJZDwK8pRrB8nGKI691k5u/K0zpfi4hDKH6XvkJxmmlSym29v6zjZRT9Ce8EvkNxK9g1ZUf3MPDeyW5fmgxHSZUkVTx9JEmqGAqSpIqhIEmqGAqSpIqhIEmqGAqSpIqhIEmq/H/9ARferNPO5AAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import seaborn as sns\n",
    "sns.histplot(data=df_train, x=\"SalePrice\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "76d4d0c2-50f1-4eaf-8b5c-97aa7cd4ce44",
   "metadata": {
    "tags": []
   },
   "source": [
    "## Data Wrangling\n",
    "\n",
    "### 1) MSSubClass int > str\n",
    "The \"MSSubClass\" category uses integers to specify types of dwelling, but these integers simply refer to categories.\n",
    "We will change the datatype of this column from int to str.\n",
    "\n",
    "<div style=\"float: left\">\n",
    "\n",
    "| Value  | Type of Dwelling |\n",
    "|---|---|\n",
    "| 20  | 1-STORY 1946 & NEWER ALL STYLES |\n",
    "|  30 | 1-STORY 1945 & OLDER |\n",
    "|  40 | 1-STORY W/FINISHED ATTIC ALL AGES |\n",
    "etc.\n",
    "\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "844dc1de-c669-4e58-b3c2-b397cbddd774",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Transformation 1: int > str\n",
    "df_train[\"MSSubClass\"] = df_train[\"MSSubClass\"].astype(\"str\")\n",
    "\n",
    "# Apply same to df_test\n",
    "df_test[\"MSSubClass\"] = df_test[\"MSSubClass\"].astype(\"str\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e266cdeb-eab9-4e11-8d55-f0ef6cc3630c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0       60\n",
       "1       20\n",
       "2       60\n",
       "3       70\n",
       "4       60\n",
       "        ..\n",
       "1455    60\n",
       "1456    20\n",
       "1457    70\n",
       "1458    20\n",
       "1459    20\n",
       "Name: MSSubClass, Length: 1460, dtype: object"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check\n",
    "df_train[\"MSSubClass\"]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "261e2610-e5ba-4c32-8ba8-08875f1dcb13",
   "metadata": {},
   "source": [
    "### 2) Make Id column index"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b8ccf287-ac8c-49ba-aa30-4a1e47a1433a",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = df_train.set_index(\"Id\")\n",
    "df_test = df_test.set_index(\"Id\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3d4fe1b4-2237-4362-b7d3-544334cee3cc",
   "metadata": {},
   "source": [
    "## Preprocessing\n",
    "\n",
    "### Numerical values\n",
    "\n",
    "- Impute missing values using the median value of the column.\n",
    "- Standardize the scale of each variable by removing the mean and scaling to unit variance (variance = 1)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "bb4b6a57-cb01-4508-8ad8-12102cf1a4e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# preprocessing for numeric columns\n",
    "imp_median = SimpleImputer(strategy=\"median\", add_indicator=True)\n",
    "scaler = StandardScaler()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "946d69a6-334a-464c-b3e8-420f28d0ee48",
   "metadata": {},
   "source": [
    "### Categorical variables\n",
    "\n",
    "- Impute a \"missing_value\" string where values are missing.\n",
    "- One hot encode all categorical variables."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "f9d81190-514c-4d64-8281-453083f1071e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# preprocessing for categorical columns\n",
    "imp_constant = SimpleImputer(strategy=\"constant\")\n",
    "ohe = OneHotEncoder(handle_unknown=\"ignore\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "604266c6-c110-4f00-bf99-e32eb837051f",
   "metadata": {},
   "source": [
    "### Create pipeline\n",
    "\n",
    "Separate numerical and categorical variables, create pipeline to implement steps defined in preprocessing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e8938ec8-ed54-4dc5-b5c3-cba5b323041d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# select columns by data type\n",
    "num_cols = make_column_selector(dtype_include=\"number\")\n",
    "cat_cols = make_column_selector(dtype_exclude=\"number\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "b1c01621-b407-4567-a8ac-07ebf0abee66",
   "metadata": {},
   "outputs": [],
   "source": [
    "# all preprocessing\n",
    "preprocessor = make_column_transformer(\n",
    "    (make_pipeline(imp_median, scaler), num_cols),\n",
    "    (make_pipeline(imp_constant, ohe), cat_cols))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "802afe1a-b9a2-4aac-890c-1f4bba8a81b1",
   "metadata": {},
   "source": [
    "## Split \"train\" dataset into train, valid datasets\n",
    "Splitting the dataset into train, valid early in the modelling process to run tests on various features."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6957697f-6136-4c36-92d7-8098dbbc3c7a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define X (independent variables) and y (dependent variable)\n",
    "X = df_train.drop(columns=\"SalePrice\")\n",
    "y = df_train[\"SalePrice\"]\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_valid, y_train, y_valid = train_test_split(X,y, test_size=0.2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "6460aed3-0b92-43d9-bfbc-aa8e4d78fba5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1168, 79)"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5335aa4f-db26-4b55-ba85-bc140283d463",
   "metadata": {},
   "source": [
    "## Construct Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "28d500fa-32d6-4202-b770-365232915670",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "\n",
    "def create_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))\n",
    "    model.add(Dense(256, activation='relu'))\n",
    "    model.add(Dense(256, activation='relu'))\n",
    "    model.add(Dense(1))\n",
    "    model.compile(optimizer=keras.optimizers.Adam(1e-3), loss=\"mse\", metrics=[\"mae\"])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "3b64a509-8bd9-458b-b01c-0b742aaf4496",
   "metadata": {},
   "outputs": [],
   "source": [
    "def densify(x):\n",
    "    return x.toarray()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "9444f3ec-81c0-4595-9be5-cfe98e2f8ddf",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.wrappers.scikit_learn import KerasRegressor\n",
    "\n",
    "model = KerasRegressor(build_fn=create_model,\n",
    "                        epochs=150,\n",
    "                        batch_size=32,\n",
    "                        verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "84876136-cf6d-4370-ac2a-f514d4c3c221",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.preprocessing import FunctionTransformer\n",
    "\n",
    "densify = FunctionTransformer(densify)\n",
    "\n",
    "pipe = Pipeline([('preprocessing', preprocessor), ('densify', densify), ('clf', model)])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c005fde0-2b78-40ce-a87d-874c84e65e37",
   "metadata": {},
   "source": [
    "Keras requires the input shape to be known before attempting to fit, so the pipeline has been executed step-by-step."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "d4a5fb87-46e9-494a-b59d-a408e37068e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Data preprocessing step\n",
    "X_train = pipe[0].fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5e3e104-37c6-495d-bd89-bcdae56ce0fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Local\\Temp/ipykernel_29084/1281600470.py\", line 2, in <module>\n",
      "    X_train = pipe[1].fit_transform(X_train)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\base.py\", line 699, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 147, in transform\n",
      "    return self._transform(X, func=self.func, kw_args=self.kw_args)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 171, in _transform\n",
      "    return func(X, **(kw_args if kw_args else {}))\n",
      "TypeError: 'FunctionTransformer' object is not callable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Local\\Temp/ipykernel_29084/1281600470.py\", line 2, in <module>\n",
      "    X_train = pipe[1].fit_transform(X_train)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\base.py\", line 699, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 147, in transform\n",
      "    return self._transform(X, func=self.func, kw_args=self.kw_args)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 171, in _transform\n",
      "    return func(X, **(kw_args if kw_args else {}))\n",
      "TypeError: 'FunctionTransformer' object is not callable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Local\\Temp/ipykernel_29084/1281600470.py\", line 2, in <module>\n",
      "    X_train = pipe[1].fit_transform(X_train)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\base.py\", line 699, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 147, in transform\n",
      "    return self._transform(X, func=self.func, kw_args=self.kw_args)\n",
      "  File \"C:\\Users\\luis_\\AppData\\Roaming\\Python\\Python37\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 171, in _transform\n",
      "    return func(X, **(kw_args if kw_args else {}))\n",
      "TypeError: 'FunctionTransformer' object is not callable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\luis_\\anaconda3\\envs\\datascience\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "# Converting from a sparse matrix to a dense array\n",
    "X_train = pipe[1].fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "39367866-227f-47fb-8928-0bf8f4594a25",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1168, 79)"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "21e1333b-3e73-4180-9741-b110af2c020b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<tensorflow.python.keras.callbacks.History at 0x1f123719848>"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Fitting the model with the newly defined shape\n",
    "pipe[2].fit(X_train,y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a07f4547-cefc-4f36-a179-362cf4c7971f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "15896add-abc1-4395-bd60-c1e648bb3421",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define X_test\n",
    "X_test = df_test\n",
    "\n",
    "# make predictions based on model\n",
    "predictions = pipe.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "eb8b5dd5-1cfe-4942-b62f-9c12d290606d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 8155.737 ,  7006.836 , 10495.487 , ..., 10392.28  ,  6810.0625,\n",
       "       11311.525 ], dtype=float32)"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "6580547e-79cc-46f0-bb94-eb246c24d95d",
   "metadata": {},
   "outputs": [],
   "source": [
    "d = {\"Id\":df_test.index,\"SalePrice\":predictions}\n",
    "submission = pd.DataFrame(data=d)\n",
    "\n",
    "# Revert log transform\n",
    "#submission[\"SalePrice\"] = np.exp(submission[\"SalePrice\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "22b277d4-81cd-458c-9d66-e3aae8854fac",
   "metadata": {},
   "outputs": [],
   "source": [
    "submission.to_csv(\"submission.csv\",index=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "21230d00-c6ed-4cb3-ad2b-1957437f6e4e",
   "metadata": {},
   "source": [
    "## Feature Engineering\n",
    "\n",
    "### 1) \"SalesPrice\" distribution\n",
    "Since the target variable \"SalesPrice\" has a long-tail distribution, we should make predictions after conducting a log transform."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2a77297-f261-4045-9da3-fa8a9b4e04ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train_fe = df_train.copy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b1914cd-28c4-4de5-9142-bd76503d5c29",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Log transform\n",
    "df_train_fe[\"SalePrice\"] = np.log(df_train_fe[\"SalePrice\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0dc549e2-4ab5-4aaa-a172-c7de88126b19",
   "metadata": {},
   "outputs": [],
   "source": [
    "sns.histplot(data=df_train_fe, x=\"SalePrice\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4f8e6b7-8f10-4136-940e-f904aa3b0aeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "print('Training set score: ' + str(pipe.score(X_train,y_train)))\n",
    "print('Validation set score: ' + str(pipe.score(X_valid,y_valid)))\n",
    "\n",
    "X_fe = df_train_fe.drop(columns=\"SalePrice\")\n",
    "y_fe = df_train_fe[\"SalePrice\"]\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "X_train_fe, X_valid_fe, y_train_fe, y_valid_fe = train_test_split(X_fe,y_fe, test_size=0.2)\n",
    "\n",
    "pipe_fe = pipe\n",
    "pipe_fe.fit(X_train_fe, y_train_fe)\n",
    "\n",
    "print('Training set score with this feature: ' + str(pipe.score(X_train_fe,y_train_fe)))\n",
    "print('Validation set score wth this feature: ' + str(pipe.score(X_valid_fe,y_valid_fe)))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
